### ISSUE TITLE
Colors for Vim terminals in Normal mode

### ISSUE THREAD

**Issue by luizpara** [jalvesaq/colorout#34]
What a life changing little plugin this is. Thanks for it!

So, I wonder if there is a way to make the coloring work also when Vim terminals go into Normal mode (by default when pressing `Ctrl-W N`). Currently, colors disappear in Normal mode. The problem that this creates is that the moment in which terminal colors would be the most helpful is precisely when putting terminals in Normal model to navigate to previous code entered and outputs generated to inspect for errors, checks past trials-and-errors, etc.

This would be even more of a life-saver, if there is a way to make it work.

**Comment by jalvesaq** [comment]
The colors output by colorout persist in Vim's terminal while in Normal mode (tested with Vim 9.0.1682 on Linux).

[Nvim-R](https://github.com/jalvesaq/Nvim-R)' syntax highlighting of the terminal only works in Neovim because Vim doesn't allow syntax highlighting of its built-in terminal. But Nvim-R' syntax highlighting of the terminal is enabled only if `colorout` isn't loaded.

**Comment by luizpara** [comment]
Thanks for your reply. But I got a bit confused about what you meant by "the colors output by colorout persist in Vim's terminal while in Normal mode", given what you said next about Vim's limitation.

Anyhow, just to be clear: I am on the same Vim version as you, on Ubuntu 22.04, and no color whatsoever from colorout persists when *the terminal itself* is in Normal mode (not the buffer containing the R script/code being worked on). As soon as I exit Normal mode, that is returning the terminal to have cursor, colors are back. The behavior is the same regardless of whether I am using Nvim-R or not (that is, whether I open the terminal with \rf or whether I uninstall Nvim-R and manually open a terminal and start a R console there).

**Comment by jalvesaq** [comment]
I'm sorry, but I can't replicate the issue as you describe it. Moreover, if colorout works as expected in a terminal emulator outside Vim, then the problem would be in Vim, not in colorout. Anyway, I suggest that you try Neovim because its built-in terminal is capable of syntax highlighting.

Another suggestion is to run `search()` in the R Console to be sure that colorout is listed among the loaded packages.

**Comment by luizpara** [comment]
@jalvesaq oh, `search()` definitively does list colorout as a loaded package. Like I said, the colorout coloring *is working normally* in the Vim built-in terminals after `library(colorout)` is run. It just completely disappears from the same Vim built-in terminals if I put those terminals in Normal mode (with `Ctrl-W N`).

**Comment by jalvesaq** [comment]
If it works in a terminal emulator (outside Vim), and if it works in Neovim's built-in terminal emulator, then, the problem is with Vim's terminal emulator. In this case, you should install the current development version of Vim from Git Hub and, if the problem persists, report the bug to Vim.
