### ISSUE TITLE
It is possible to change the background color only of the R console?

### ISSUE THREAD

**Issue by SoaresAlisson** [jalvesaq/colorout#43]
Well, I don't know if it is a question of `colorout`, `R.nvim`, nvim or to my terminal, but I use my second screen in vertical and sometimes the editor and the R console becomes almost indistinguishable. It is possible to change the background color only of the R console using colorout or in any other way?

Thanks!

**Comment by jalvesaq** [comment]
I'm unsure if you should implement this because `colorout` is supposed to colororize R's output, not set terminal colors.

The built-in Neovim terminal doesn't support escape codes to change the background color. But, if running R directly in a terminal emulator, not within Neovim, you can add to your `~/.Rprofile`:

```r
cat("\x1b]11;#001520\x1b\\")
on.exit(cat("\x1b]11;black\x1b\\"))
```

The problem is that the `on.exit()` isn't working on my side. So, maybe you could configure this in your terminal emulator. Instructions for `kitty`: https://sw.kovidgoyal.net/kitty/faq/#how-do-i-change-the-colors-in-a-running-kitty-instance
